### ISSUE TITLE
Question: taking db resourses

### ISSUE THREAD

**Issue by VladisS-Vostok2000** [Zicore/CrossoutMarket#112]
Hello there!
Im not really into programming, but i done crossout calc with my own features to make trading much better.
It's working actually, but its extremly hard to input all the prices in.
So i'm asking, is there any way to get file with products prices?
I don't know, is it legal or not to take it from my private account and how; and if it isnt, to how get it from here.
Thanks!

**Comment by Stiffi136** [comment]
Sorry for the late answer, I'm not checking the issues very often.
We offer an API for external applications to get the data from CrossoutDB. However, this requires a bit of programming. 
The easier way to get up to date prices is through a google spreadsheet. Instructions on how to import data into your spreadsheet can be found here: https://crossoutdb.com/export . If you have further questions on how to set this up you can join our Discord: https://discord.gg/D3TQtm5
