### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Meirerion** [Zicore/CrossoutMarket#19]
Hi, I've seen that you wanted bugs etc reported here. Here's my list:

- ST-M23 Defender: 3x Lupara (not Chord); 2x cannon (not WWT1)
- LM-54 CHORD: 3x 100 scraps and not 300 x 100 scraps (the mistake is everywhere you can show the LM's craft).

Haven't found any more but will update if I see any.

As always, thanks for the website and have a beautiful day!

**Comment by Stiffi136** [comment]
Many recipes are still from the closed beta. Since this is a manual process we have to check and update all recipes by hand, but we're working on it.

**Comment by Zicore** [comment]
Should be fixed, thank you for your help.
