### ISSUE TITLE
Incorrect recipes

### ISSUE THREAD

**Issue by thalur-ksp** [Zicore/CrossoutMarket#20]
I've found a couple of incorrect epic recpies:

Nomads:
- Spectre-2 should be attack drone and ST-M23 defender instead of chained wheel and hazardous generator
- AC72 Whirlwind should be judge 76mm instead of large wheel

Lunatics:
- Cricket 1M should be spitfire and explosive spear instead of docker and small track

**Comment by Stiffi136** [comment]
Many recipes are still from the closed beta. Since this is a manual process we have to check and update all recipes by hand, but we're working on it.

**Comment by Zicore** [comment]
Should be fixed, thank you for your help.

**Comment by RA2lover** [comment]
Lunatics:
- Light engine uses WWT1 cabin, should be Docker
- Growl cabin lists 3 Avia boosters, and 2 dockers/chords - should be 3 dockers, 2 boosters/chords.
- Small tracks are listed as using 2 large wheels/ST, should use 2 Chained wheels/ST

Nomads:
-ST-M23 Defenders use Small wheel/WWT1/3x Chords - should be 2 Small Wheel ST/Avengers, and 3 Luparas

Haven't checked other factions myself at the moment.

**Comment by Stiffi136** [comment]
Thanks for the report, we fixed it.
If you find any bugs in the future, please open a new issue.
