### ISSUE TITLE
Crafting Profit as extra column

### ISSUE THREAD

**Issue by Rawsted** [Zicore/CrossoutMarket#35]
So i just put it here 
sorry if this is wrong.

my idea is to add a "sort by profit" button anywhere. i want to play the market a bit and checking every single weapon and item is too much work, that this Page already hase done for me.

**Comment by Rawsted** [comment]
ok i found s.o. already done this so Issue closed

https://github.com/agentd00nut/crossout_crafting_profiter

**Comment by Zicore** [comment]
Thank you. This way of submitting an Idea is perfectly fine, we are planning crafting profit feature, but it will probably take a while.

**Comment by Rawsted** [comment]
I just found s.o. who already did in python I actualized his work.
In fact it is using ur website crossoutdb.com to calculate everything shall
I show you the code?

Am 09.08.2017 13:20 schrieb "Andre" <notifications@github.com>:

**Comment by Stiffi136** [comment]
Implemented as part of 94c30d9c3cb292d0b8ea79bcb98d5942ada7c24b
