### ISSUE TITLE
Unpaking game files

### ISSUE THREAD

**Issue by Mirolog** [Zicore/CrossoutMarket#47]
Hi, @Zicore , you did an awesome job on this market tool, it's extremely useful!

I've seen in FAQ that you have tools required to unpack Crossout game's archives. Is there any way for me to get this tool? I really want to make some cool Crossout-related renders using game assets.

On the legal note, I'm a Star Conflict tester at the moment and I've signed an NDA with Targem Games. So I'm not going to use data found in the game to somehow interfere with game development (and I'm not going to sell it and whatnot) 

Thanks.

**Comment by Johnnynator** [comment]
You can use http://aluigi.altervista.org/quickbms.htm with the clutch (another game form targem) script.
And also if I remember correctly then just dicking around in the game files is absolutely fine for them, if you want to make some renders with their models you probably should ask them before.
