### ISSUE TITLE
DateTime timezone info in API

### ISSUE THREAD

**Issue by mickdekkers** [Zicore/CrossoutMarket#50]
In the API there are a few fields with a DateTime type, e.g. the `timestamp` in the `item/{id}` endpoint.

They seem to be in ISO 8601 format (`{full-date}T{full-time}`), but lack a timezone.
This makes these fields difficult to parse, because API consumers essentially have to guess the timezone.

The reason why this is happening is because when Json.NET serializes DateTimes, it does not produce any time zone information by default.

A straight-forward solution to this problem would be to [use the DateTimeOffset type instead of DateTime](https://stackoverflow.com/a/25105519).

**Comment by Zicore** [comment]
All times should be UTC now.
