### ISSUE TITLE
[Help Wanted] Documentation or explanations on profits

### ISSUE THREAD

**Issue by sholan** [Zicore/CrossoutMarket#54]
Dear (pretty damn good) Developpers,

I have been using Crossoutdb since started the game and found price history to be really usefull, now I am decided to move step forward and create to earn money.

When using the website, I face a huge difficulty understanding several things: 
- What is profit in both sell and buy columns
- What is Sell-Buy Profit

I looked for help in both README.md and on crossout forum and didn't find anything useful.
Is there a place I didn't look for ?

Carry on, you're doing great.

Regards,
sholan

**Comment by Zicore** [comment]
In a market like this you have two options to buy or sell something.
First: Instantly buy/sell something from other players offers.
Second: Make a buy/sell order and wait until someone buys from you or sells to you.

The second option is allways better as long as it's not time critical.

So if you buy with buy orders and sell with sell orders you make the most profit.
Sell (Offers) - Buy (Orders) = Maximum Profit.

**Comment by sholan** [comment]
I think you just explained the "margin" data not, the sell-buy profit, otherwise, application calculations are just incorrect.

**Comment by littledaxter** [comment]
+1 Some kind of documentation about the margin, both profit and buy/sell profits would be great!

**Comment by sholan** [comment]
The video tour recently added to the website (https://www.youtube.com/watch?v=EwvR_57ZCaw)
Addresses this issue perfectly.

I consider this answer given by this video suitable.

**Comment by Stiffi136** [comment]
There is now also a steam guide available: http://steamcommunity.com/sharedfiles/filedetails/?id=1119609425
