### ISSUE TITLE
feature request: customizable time zone in graphs

### ISSUE THREAD

**Issue by littledaxter** [Zicore/CrossoutMarket#56]
Hi guys!

I've just discovered this project and i LOVE it, especially the graph part for items (i'll try to make a buck trading basic scraps while analysing your stats on it's variations).

I just noticed that my time zone is off from the data on the site (or you just happen to have a 20h delay).
I know it's just 'fluff' and a nice-to-have feature but i'd really like it. Thanks!

**Comment by Stiffi136** [comment]
Timestamps are now based on local time

**Comment by littledaxter** [comment]
Great work! Thanks a lot!
