### ISSUE TITLE
Download whole market data at once?

### ISSUE THREAD

**Issue by andrewpros** [Zicore/CrossoutMarket#59]
Hi.

Would it be possible to have an option to download whole market data at once?

I dont know, by api or maybe a highly compressed file updated every 5 minutes as the default interval?

I want to run this site locally and make some changes for my needs, but getting all the market items one by one just dont seem very efficient.

**Comment by Zicore** [comment]
Hmm, I think this would kill our server 😄

**Comment by andrewpros** [comment]
Well i forgot to mention, no all market data, but just for the current 5 minute interval, all items.

I have found out the item api already returns an item array even if u can request only single id at time, it would be nice to have an option to get multiple items with one call.

**Comment by andrewpros** [comment]
Oh and one more thing, what is the difference? If it is not possible by a single call, then i need to make at least several dozen api calls? Right?

**Comment by Stiffi136** [comment]
You could use https://crossoutdb.com/api/v1/items to get all items by a single call.

**Comment by andrewpros** [comment]
Well that will be ok. Thx.
