### ISSUE TITLE
Suggestion: Historical Price Chart should always use the highest data resolution avaliable

### ISSUE THREAD

**Issue by silvercheckmate** [Zicore/CrossoutMarket#63]
I find that when I check on an item's price history, any search duration longer than 12 hrs results in the price graph being averaged. And hence you do not see the true highs and lows. I would imagine there are legit uses for high resolution data as well as an average, so maybe this could be another toggle option for the user?

**Comment by Stiffi136** [comment]
Implemented with ed72a531dfea78b81d4d524c9cf3535e60c41411 .
