### ISSUE TITLE
Bug: Historical Price Chart Buy/Sell numbers are false when search duration is larger than 12 hours

### ISSUE THREAD

**Issue by silvercheckmate** [Zicore/CrossoutMarket#64]
This is linked to #63. If the search duration is larger than 12 hours, the buy/sell count becomes inaccurate. I suspect that as data points become merged together, buy/sell numbers are added together instead of being averaged, leading to bloated inaccurate numbers.

To verify the bug, simply compare the buy/sell figures for the latest data point that 12 hrs vs 1day gives you. Numbers are bloated up.

**Comment by Stiffi136** [comment]
Fixed with ed72a531dfea78b81d4d524c9cf3535e60c41411 .
