### ISSUE TITLE
Bug: Changing filters reloads page, causes pagination and sorting settings to be lost.

### ISSUE THREAD

**Issue by silvercheckmate** [Zicore/CrossoutMarket#67]
Selecting another filter reloads the entire page, it should be ajax driven like the column sorting and search no? Either way the page reloads causes pagination and existing sorting settings to be lost.

**Comment by Stiffi136** [comment]
Has been fixed with 20db30e28db1a4ddc9bfc2d8d4dc1aa3b6af5734
