### ISSUE TITLE
Save table filters by cookie.

### ISSUE THREAD

**Issue by Zicore** [Zicore/CrossoutMarket#82]
As requested here: https://github.com/Zicore/CrossoutMarket/issues/66#issuecomment-351979524

**Comment by andrewpros** [comment]
Yeah, that would be super helpful, right now u need to set all the filtering again every refresh, it would also nice if we could save the default entries showed.

**Comment by andrewpros** [comment]
Or maybe not cookie, could we use pjax or some kind of push browser history api?
Just not cookie, as cookie will stay there and set filtering even if someone dont want to anymore, a lot issue with. a cookie solution, it would be best to leverage normal url filtering as it was before, but now in a more clever way, no reload, just push new url.

**Comment by Stiffi136** [comment]
I also would prefer not to use cookies for this. However I'm not completly sure about how to implement it yet.

**Comment by andrewpros** [comment]
Well i see it simple, every time any filter option is pressed the browser url is changed to reflect it with the use of history pushState api.
This is the simplest way currently to keep how the filters work now, without reloading page, i think this should not be changed, and yet provide an url for manual refresh purposes or saving a direct link.

**Comment by Stiffi136** [comment]
Implemented with 9a442d7bfc71925f8a151d9debc25dab2fc94aa0
