### ISSUE TITLE
Increase refresh rate

### ISSUE THREAD

**Issue by glmn** [Zicore/CrossoutMarket#84]
Hi. Is it possible to increase data refresh rate to atleast 1 minute?

**Comment by Stiffi136** [comment]
The refresh rate is currently limited to 5 minutes by the API from targem. We could ask them to lower it even further (as we asked them already to lower it). However I would like to know why a higher refresh rate is needed. Also keep in mind that a higher refresh rate means more data we have to display in the item graphs.

**Comment by andrewpros** [comment]
Well i dont think anything lower than 5 minutes is needed, there is no point.

**Comment by Zicore** [comment]
Currently not possible from the API and not really wanted right now. We don't aim to offer realtime data, we aim to provide current and more importantly historic data with some features on top.
