### ISSUE TITLE
Suggestion: Make market data more informative

### ISSUE THREAD

**Issue by coldfir3** [Zicore/CrossoutMarket#85]
Is it possible to change the market graph to candle graph, so we can know the opening and closing prices of the time-step?

Also, is there anyway to gather the full bid list, even if its under some API? it would be really nice to know this information so we could find price supports for some itens. This is key to speculate future price.

Cheers, and keep the good work!

**Comment by Zicore** [comment]
Sorry, this is not possible for different reasons. The biggest problem is, we don't have actual trade data.
