### ISSUE TITLE
Minor Naming Convention Issue

### ISSUE THREAD

**Issue by BuildBodger** [Zicore/CrossoutMarket#87]
Hi, I've noticed that in the items API the stat for "ProjectileVelocity" doesn't fit your normal naming convention.  I figure it should be "StatProjectileVelocity" based on the other names found in there.

I don't want to be a pest, just want to help improve this awesome website.  Let me know if this kind of issue is helpful or not.

**Comment by Zicore** [comment]
Fixed with: https://github.com/Zicore/CrossoutMarket/commit/96210a30c2391070632e7557100bf71d84a0d866
