### ISSUE TITLE
Bug: Items in wrong category

### ISSUE THREAD

**Issue by knifers** [Zicore/CrossoutMarket#91]
https://crossoutdb.com/item/606
Asmodeus - Already in Decor, should be in Dyes

https://crossoutdb.com/item/481
Pattern: Lava -  Already in Decor, should be in Dyes

https://crossoutdb.com/item/400
Embers - Already in Decor, should be in Dyes

**Comment by Stiffi136** [comment]
Thanks for the issue.
Asmodeus is now categorized as Customization.
Pattern: Lava is now categorized as Dyes.
Embers is now categorized as Dyes.
